import Head from 'next/head';
import Topbar from '../components/Topbar';
import Center from '../components/Center';
import Instructions from '../components/Instructions';

export default function Home() {
    return (
        <div className="flex flex-col h-screen">

            <Head>
                <title>Spotify Set Operations</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <div className='bg-gradient-to-br from-purple-800 to-violet-900'>
                <Topbar />
                <Center />
            </div>

            <Instructions />

        </div>
    );
};
