import Head from 'next/head';
import Topbar from '../components/Topbar';
import Center from '../components/Center';

export default function Home() {
  return (
    <div className="">

      <Head>
        <title>Spotify Set Operations</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className='bg-gradient-to-br from-emerald-500 to-lime-600 h-104'>
        <Topbar />
        <Center />
      </div>

    </div>
  );
};
